### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EmilianoSutil**
Spanish translation of the QRC

### CODE REVIEW

**Comment by matthewskelton** [comment]
Any chance of linking to a higher-resolution image, @EmilianoSutil ?

**Comment by matthewskelton** [comment]
Hi @EmilianoSutil - apologies, I left this PR too long before reviewing. Any chance you could rebase first, then resubmit? The link itself it great :)

**Comment by EmilianoSutil** [comment]
Hi @matthewskelton I have resolved the conflicts. Please review if this is correct.

**Comment by matthewskelton** [comment]
Thanks, @EmilianoSutil !

**Pull request merged**
